theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
author: sarungunz

title: ThailandElection-and-AgeDistribution
description: Naive analysis of the effect of age distribution of voters on Thailand election 2019 
